# Generated by Django 4.0.6 on 2022-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='remaining_amountt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter remaing amount', max_digits=10, null=True),
        ),
    ]
